### ISSUE TITLE
Circuit Construction Kit: AC - Virtual Lab Main Checklist

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-ac-virtual-lab#1]
# CCK: AC - Virtual Lab Main checklist

**Note: since this sim is essentially the same as CCK AC but without noncontact ammeters, most of the design items have been removed and will be covered by https://github.com/phetsims/circuit-construction-kit-ac/issues/1**

## Design
- [ ] **Pre-publication items**
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Accessibility features
  - [ ] Email announcement language
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [ ] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [ ] **Make sim visible on website** 
   - [ ] Clear "Metadata caches" on the [Basic Administration Caches](https://phet.colorado.edu/?wicket:bookmarkablePage=:edu.colorado.phet.website.admin.AdminCachesPage) page
- [ ] **Post-publication items**
  - [ ] *If a Port:* Review legacy gold star activities, copy over if appropriate
  - [ ] Share new features, design challenges, and treats with group!
  - [ ] Email announcement
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Create "sim primer" issue

## Implementation
- [x] **Repository created** (Date: 01/11/2021)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 01/11/2021)
- [x] **Sim is "feature complete"** (Date: 01/11/2021?)
- [x] **Code review completed** (Date: 05/19/2021)
- [ ] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [x] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks)
  - [ ] Add CT tests for public query parameters
- [ ] **Published** (Date: //)
  - [ ] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [ ] **Dev testing started** (Date: //)
- [ ] **Dev testing completed** (Date: //)
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)
